### ISSUE TITLE
Which data is hand annotated?

### ISSUE THREAD

**Issue by TheresaSchmidt** [ozgen/dataset_for_recipe_tagger#1]
Hi,

Quick question: which part of the data is hand annotated?
And which data did you use to train and evaluate your model (i.e. how can I reproduce the results from your thesis)?

Also, did you use the brat tool for annotation?

Thanks in advance :)

**Comment by ozgen** [comment]
Sorry for late answer, This data is not hand annotated. I used unsupervised learning for this step. https://github.com/ozgen/ingredient-phrase-tagger model is used for ingredient parser. other words in the sentence are tagged with PosTagging and check the word is verb and also tool dictionary ( like pan, oven etc. ) is used for that. Main Repo for the thesis  is https://github.com/ozgen/recipe-postagger
